#server:
#  port: 8180
#  ip: ${spring.cloud.client.ip-address}
#spring:
#  application:
#    name: gateway
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
#      loadbalancer:
#        use404: true # false:当在LoadBalancer找不到服务实例时，将返回503, true: 返回404
#  datasource:
#    druid:
#      driver-class-name: com.mysql.jdbc.Driver
#      url: jdbc:mysql://127.0.0.1:3306/xxl_job
#      password: root
#      username: root
#      min-idle: 5
#      max-active: 10
#      max-wait: 10000
#      initial-size: 5
#
#
#mybatis:
#  mapper-locations: classpath:config/mapper/*.xml
#logging:
#  config: classpath:config/log/logback.xml
#  level:
#    com.alibaba.nacos.client.config.impl.ClientWorker: WARN
#
#
